package com.masroofy.model;

/**
 * Represents a financial transaction (expense entry) for budget tracking.
 * <p>
 * This class encapsulates transaction details including the amount spent,
 * category classification, transaction date, and the associated user ID.
 * </p>
 *
 * @author Nada
 * @version 1.0
 */
public class Transaction {
    private int transactionId;
    private int userId;
    private double amount;
    private int categoryId;
    private String date;

    /**
     * Constructs a new Transaction without an ID.
     * <p>
     * Used when creating new transactions that don't yet exist in the database.
     * The transaction ID will be generated by the database.
     * </p>
     *
     * @param userId the unique identifier of the user who made this transaction
     * @param amount the transaction amount (in currency units)
     * @param categoryId the expense category ID (1-7 range)
     * @param date the transaction date (in YYYY-MM-DD format)
     */
    public Transaction(int userId, double amount, int categoryId, String date) {
        this.userId = userId;
        this.amount = amount;
        this.categoryId = categoryId;
        this.date = date;
    }
    
    /**
     * Constructs a Transaction with a transaction ID.
     * <p>
     * Used when updating existing transactions or retrieving from the database.
     * </p>
     *
     * @param transactionId the unique identifier of this transaction
     * @param userId the unique identifier of the user who made this transaction
     * @param amount the transaction amount (in currency units)
     * @param categoryId the expense category ID (1-7 range)
     * @param date the transaction date (in YYYY-MM-DD format)
     */
    public Transaction(int transactionId, int userId, double amount, int categoryId, String date) {
        this.transactionId = transactionId;
        this.userId = userId;
        this.amount = amount;
        this.categoryId = categoryId;
        this.date = date;
    }

    /**
     * Gets the user ID associated with this transaction.
     *
     * @return the user ID
     */
    public int getUserId() {
        return userId;
    }
    
    /**
     * Gets the transaction ID.
     *
     * @return the transaction ID, or 0 if not yet persisted
     */
    public int getTransactionId() {
        return transactionId;
    }

    /**
     * Gets the transaction amount.
     *
     * @return the amount spent
     */
    public double getAmount() {
        return amount;
    }

    /**
     * Gets the expense category ID for this transaction.
     *
     * @return the category ID (1=Food, 2=Transport, 3=Entertainment, 4=Shopping, 5=Health, 6=Education, 7=Other)
     */
    public int getCategoryId() {
        return categoryId;
    }

    /**
     * Gets the transaction date.
     *
     * @return the date in YYYY-MM-DD format
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the transaction amount.
     *
     * @param amount the new amount to set
     */
    public void setAmount(double amount) {
        this.amount = amount;
    }

    /**
     * Sets the expense category ID for this transaction.
     *
     * @param categoryId the new category ID to set (1-7 range)
     */
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * Sets the transaction date.
     *
     * @param date the new date to set (in YYYY-MM-DD format)
     */
    public void setDate(String date) {
        this.date = date;
    }
}
